version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: garden_redis_prod
    restart: always
    ports:
      - "6379:6379"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: garden_mosquitto_prod
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  rest_api:
    image: ghcr.io/felipesantander/garden.homesuit.cl/rest-api:0.0.1
    container_name: garden_rest_api_prod
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mongodb://root:example@192.168.1.134:27017/
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    depends_on:
      - redis
      - mosquitto

  mqtt_worker:
    image: ghcr.io/felipesantander/garden.homesuit.cl/rest-api:0.0.1
    container_name: garden_mqtt_worker_prod
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mongodb://root:example@192.168.1.134:27017/
      - REDIS_HOST=redis
      - MQTT_HOST=mosquitto
    command: python manage.py mqtt
    depends_on:
      - mosquitto
      - redis
